### ISSUE TITLE
comment with msgid in headed causes problems on damned-lies

### ISSUE THREAD

**Issue by scootergrisen** [translate/translate#4308] opened 2021-04-01 21:12 UTC
On https://l10n.gnome.org/module/gnome-user-docs/ is/was a po file with incorrect information about how many strings are translated, fuzzy and untranslated in the commited po file.

Damned-lies just says 1 untranslated string.

As reported in https://gitlab.gnome.org/Infrastructure/damned-lies/-/issues/220 someone says the follow line in the header causes it and suggest reporting it here also.

`# scootergrisen:    msgid "View your battery status and change power saving settings"`

**Comment by claudep** [comment] 2021-04-01 21:16
The file with the issue: https://gitlab.gnome.org/GNOME/gnome-user-docs/-/blob/a291070699de4cfb/gnome-help/da/da.po
Parsing that file with the po parser wrongly gives only one unit.

**Comment by nijel** [comment] 2021-04-02 05:00
Which translate-toolkit version do you use there? 

It seems to count correctly for me:

```
$ pocount /tmp/gnome-help_da_da.po 
Processing file : /tmp/gnome-help_da_da.po
Type               Strings      Words (source)    Words (translation)
Translated:    2301 ( 70%)      28899 ( 50%)           26796
Fuzzy:            0 (  0%)          0 (  0%)             n/a
Untranslated:   975 ( 29%)      28832 ( 49%)             n/a
Total:         3276             57731                  26796

Unreviewed:    2301 ( 70%)      28899 ( 50%)           26796
Empty:          975 ( 29%)      28832 ( 49%)               0
```

**Comment by claudep** [comment] 2021-04-02 07:12
version 3.3.3

```
$ pocount /tmp/gnome-help.master.da.po 
Processing file : /tmp/gnome-help.master.da.po
Type               Strings      Words (source)    Words (translation)
Translated:       0 (  0%)          0 (  0%)               0
Fuzzy:            0 (  0%)          0 (  0%)             n/a
Untranslated:     1 (100%)       4530 (100%)             n/a
Total:            1              4530                      0

Empty:            1 (100%)       4530 (100%)               0
```

**Comment by nijel** [comment] 2021-04-02 07:21
Strange, it works fine for me with 3.3.3 (and few other older releases I've tried). Are you using the file linked from https://github.com/translate/translate/issues/4308#issuecomment-812177486?

**Comment by nijel** [comment] 2021-04-02 07:26
Okay, I can reproduce it with https://l10n.gnome.org/POT/gnome-user-docs.master/docs/gnome-help.master.da.po, but not with https://gitlab.gnome.org/GNOME/gnome-user-docs/-/blob/a291070699de4cfb/gnome-help/da/da.po. 

The problem is caused by using DOS newlines in the comment and Unix in rest of the file - it makes the parser assume whole file uses DOS newlines, and thus it parses no lines further.

**Comment by claudep** [comment] 2021-04-02 07:27
Oh, wait, no, I think the problem arises only when the file is merged with the pot file. Let me upload a sample to reproduce.

**Comment by nijel** [comment] 2021-04-02 07:33
https://github.com/translate/translate/pull/4310 addresses the issue I could reproduce.

**Comment by claudep** [comment] 2021-04-02 07:33
```
# Danish translation for gnome-user-docs.
# Copyright (C) 2015 gnome-user-docs's COPYRIGHT HOLDER
# This file is distributed under the same license as the gnome-user-docs package.
# scootergrisen, 2015-2016, 2019-2021.
# Gennemgået Ask Hjorth Larsen <asklarsen@gmail.com>, 2016.
# 
# scootergrisen: rettelser til gnome-control-center:
# scootergrisen:    har forkert oversættelse af "power saving" (strømstyring/strømbesparelse):
# scootergrisen:    msgid "View your battery status and change power saving settings"
# scootergrisen:
# 
msgid ""
msgstr ""
"Project-Id-Version: gnome-user-docs master\n"
"POT-Creation-Date: 2021-04-01 16:41+0000\n"
"PO-Revision-Date: 2021-01-07 00:00+0200\n"
"Last-Translator: scootergrisen\n"
"Language-Team: Danish\n"
"Language: da\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#. (itstool) path: p/link
#: C/legal.xml:3
msgid "Creative Commons Attribution-ShareAlike 3.0 Unported License"
msgstr ""
"Creative Commons Kreditering-Deling på samme vilkår 3.0 Ikke porteret-licens"

#. (itstool) path: license/p
#: C/legal.xml:3
msgid "This work is licensed under a <_:link-1/>."
msgstr "Værket er licenseret under en <_:link-1/>."

#. Put one translator per line, in the form NAME <EMAIL>, YEAR1, YEAR2
msgctxt "_"
msgid "translator-credits"
msgstr "scootergrisen <>, 2015-2016, 2019-2021"

#. (itstool) path: info/desc
#: C/a11y-bouncekeys.page:36
msgid "Ignore quickly-repeated key presses of the same key."
msgstr "Ignorér hurtige gentagne tastetryk på den samme tast."
```

**Closed** 2021-04-02 10:46 UTC

**Comment by claudep** [comment] 2021-04-02 17:58
Thanks a lot @nijel for the quick resolution!
