### ISSUE TITLE
php2po comma issue

### ISSUE THREAD

**Issue by beachmat** [translate/translate#3284] opened 2015-08-11 15:38 UTC
I'm having problems with translatable text in a `figcaption` element not being exported with `php2po`. Should it work? It's odd because with another `figcaption` element in the same file it's ok.

**Comment by beachmat** [comment] 2015-08-11 16:04
It appears to be to do with brackets in the figcaption text. If you remove them the problem does not occur.
```
<figure class="figure-story left">
                                              <img class="margin-bottom-0-5rem" alt="" src="/img/camps/za/abdul-farida.jpg" />
                                              <figcaption>Left to right: Abdul, Nada (12), Nisreen (14), Younes (16), Inaam (5), Sihan (10) and Ibrahim (7). Eldest daughter Nora (16) was not present when this photo was taken.</figcaption>
                                              </figure>
```

**Comment by beachmat** [comment] 2015-08-11 16:32
To be more specific, it seems to be a closing bracket followed by a comma within the figcaption that is causing the problem.

**Comment by beachmat** [comment] 2015-08-11 16:52
Having a similar problem with text following a comma within a li element not being exported, so it seems it's the comma that causing it.

**Comment by beachmat** [comment] 2015-08-11 17:36
Now tried TTK 1.13 and no difference from 1.12

**Comment by unho** [comment] 2015-08-11 19:06
> I'm having problems with translatable text in a `figcaption` element not being exported with `php2po`.

You should use `html2po` instead to convert HTML code. Please try again and let us know if it works.

**Comment by beachmat** [comment] 2015-08-11 19:16
Nothing happens with html2po. These are PHP files with embedded HTML, not HTML files with embedded PHP.

**Comment by unho** [comment] 2015-08-11 19:40
I am afraid that `php2po` doesn't support extracting translatable content from HTML code, independently on where it is. And `html2po` won't work either in mixed formats scenario. I suggest you to don't mix them.

Closing this as wontfix.

**Closed by unho** 2015-08-11 19:40 UTC

**Comment by beachmat** [comment] 2015-08-11 20:13
Ok, but php2po doesn't need to extract the text from within HTML tags. It simply needs to extract the tags and text together, that are within the array value, rather than not extract them. The translation tool can then handle the presentation of the tags.

**Comment by unho** [comment] 2015-08-11 21:17
> It simply needs to extract the tags and text within the array value together, as they are, rather than not extract them.

Then you are presenting the translator a string to translate that has twice the size it really needs. I don't find these particularly translator-friendly.

The problem is that this is neither PHP nor HTML, there are commas involved and you are trying to use `php2po`. This is a very specific, really uncommon scenario. From a translator friendly point of view these two formats shouldn't be mixed in order to be allow to use a more tailored tool (`html2po`) in order to extract just what needs to be translated. I honestly think the same applies from an engineering point of view if you use the MVC pattern, something that I strongly advise to follow, you will have more structured code that is easier to maintain, and to extract translatable text from. So we are not going to provide a fix for this.

If this is your project then please adjust your file to what Translate Toolkit supports. If it is not then please push your developer to use more translator friendly approaches.
