### ISSUE TITLE
rc2po gives no error but empty file

### ISSUE THREAD

**Issue by Tyrben** [translate/translate#4849] opened 2023-03-01 14:01 UTC
## How to reproduce

1. Prepare an .RC file in a lang/ subfolder
2. - you can take any good formatted .rc , or I could provide one
3. - for a simple test, it should be encoded in utf-16LE
4. Prepare an empty po/ subfolder
5. From the common directory, run  `rc2po -charset=utf-16 lang/ po/`

A good candidate can be this file (free software):
https://github.com/m417z/7-Taskbar-Tweaker/blob/master/exe/rsrc.rc

## Result
- the po/ contains an empty po file,
- the command says "processing 1 files... 100%"
- no error

If the traceback are activated (add `--errorlevel=traceback` to your command) you should obtain that:

> rc2po.py: WARNING: Error processing: input lang/MapDraw.rc, output pot/MapDraw.po, template None: Traceback (most recent call last):
> 
>   File "C:\Users\Tyrben\AppData\Local\Programs\Python\Python311\Lib\site-packages\translate\misc\optrecurse.py", line 607, in recursiveprocess
>     success = self.processfile(
>               ^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\Tyrben\AppData\Local\Programs\Python\Python311\Lib\site-packages\translate\convert\convert.py", line 233, in processfile
>     return super().processfile(
>            ^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\Tyrben\AppData\Local\Programs\Python\Python311\Lib\site-packages\translate\misc\optrecurse.py", line 687, in processfile
>     if fileprocessor(inputfile, outputfile, templatefile, **passthroughoptions):
>        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "D:\git\autres\translate\translate\convert\rc2po.py", line 113, in convertrc
>     input_store = rc.rcfile(input_file, lang, sublang, encoding=charset)
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\Tyrben\AppData\Local\Programs\Python\Python311\Lib\site-packages\translate\storage\rc.py", line 335, in __init__
>     self.parse(
> 
>   File "C:\Users\Tyrben\AppData\Local\Programs\Python\Python311\Lib\site-packages\translate\storage\rc.py", line 396, in parse
>     self.parse(rcsrc, expected_encoding)
> 
>   File "C:\Users\Tyrben\AppData\Local\Programs\Python\Python311\Lib\site-packages\translate\storage\rc.py", line 374, in parse
>     decoded = rcsrc.decode(encoding)
>               ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\Tyrben\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 16, in decode
>     return codecs.charmap_decode(input,errors,decoding_table)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

See that it uses the *cp1252* decoder. 

Other tests with utf-8 and utf-8BOM files were made, the error is mol the same.

## Expected
- some errors
- some warnings
- some verbosity
- 1 .po file with at least something in it

Error found. I expect a message such as

> "utf-16" is not a valid encoding, choose "utf-16LE" or "utf-16BE"

## Infos

rc2po version 3.8.4
python 3.11.2 Windows

**Comment by luebbe** [comment] 2024-02-19 09:04
I've come across this problem too when trying to import a .rc file. The progress bar goes to 100%, an zero byte output file is visible in the windows explorer while rc2po.exe is running. When the process is finished, the file gets removed. Adding --errorlevel=traceback to the command line doesn't produce any additional output.

**Comment by nijel** [comment] 2024-02-19 10:05
@luebbe Then your issue seems different because the OP had issue with the file encoding and in your case the parser didn't detect anything to convert in the file. Can you please open a separate issue, including the reproducer RC file?

Speaking of the reproducer, I can't reproduce this issue either. The referenced RC file converts just fine in both the current version and in 3.8.4. My wild guess is that the file was containing `#pragma` directive for encoding and handling of that was fixed in c07d9fcc0eebc68afdcb60989f30c4694d19c4ef. Or it might have been fixed by 7e8ad77fe3130c8616b296cd9a6110d3796b6a86, but that was already present in the 3.8.4.
Anyway, I'm closing this as fixed until there is a way to reproduce this issue.

**Closed by nijel** 2024-02-19 10:05 UTC

**Comment by luebbe** [comment] 2024-02-19 10:33
Thanks for the feedback @nijel . I'm trying to figure out, why weblate doesn't parse any strings from the .rc file in question, so I tried with rc2po on the command line and this issue looked like a match to me. Unfortunately I won't be able to provide the exact .rc file, because it's internal. I will try to narrow it down and hopefully I can create something that reproduces the error.
