### ISSUE TITLE
PHP: Can't parse if newline between delimiter and value

### ISSUE THREAD

**Issue by unho** [translate/translate#3628] opened 2017-05-30 18:03 UTC
Reported by @rimas-kudelis:

When there is a newline after delimiter (`=>` in the example below) and the value within an array the parser doesn't work:

```php
<?php
return array(
    'parent3'=> array(
            'key1' =>
                'value2',
        ),
);
```

**Comment by rimas-kudelis** [comment] 2017-05-30 20:30
This looks like a dupe of #2647.

**Comment by unho** [comment] 2017-06-01 07:40
Yes, part of what is on this issue is already covered by https://github.com/translate/translate/issues/2647. I am repurposing this issue.

**Closed** 2018-03-05 21:30 UTC
Labels: formats
