### ISSUE TITLE
resx2po name into msgid

### ISSUE THREAD

**Issue by jraby-adoria** [translate/translate#4710] opened 2022-08-25 12:46 UTC
Name is inserted a comment, is it possible to insert it in "msgid" and the value in "msgstr"?

```
<data name="RegisterAsNewUser" xml:space="preserve">
  <value>Register as a new user</value>
</data>
```
```
msgid "RegisterAsNewUser"
msgstr "Register as a new user"
```

**Comment by nijel** [comment] 2022-08-26 07:16
Duplicate of #4415

**Closed by nijel** 2022-08-26 07:16 UTC
