### ISSUE TITLE
Where is the windows installer?

### ISSUE THREAD

**Issue by Joe-U-Questionmark** [translate/translate#3272] opened 2015-05-26 14:53 UTC
In the installation notes a windows installer is referenced by I see no sign of it. 
Where can I find it?

**Comment by unho** [comment] 2015-05-26 15:08
The last version with a Windows installer is https://sourceforge.net/projects/translate/files/Translate%20Toolkit/1.9.0/

Marking this as a duplicate of #3162.

**Closed by unho** 2015-05-26 15:08 UTC
